<?php

return [

    // المجموعة الافتراضية عند عدم تحديد $set صراحة
    'default_set' => 'bi', // ion | fa | bi | heroicon | svg

    // الحجم الافتراضي (width/height) المحقون في أيقونات SVG/heroicon التي ماعندهاش
    // حجم محدد في الملف الأصلي — يمنع ظهورها بحجم كبير جدًا بلا CSS إضافي.
    // '1em' يخليها تتبع حجم الخط المحيط بها تلقائيًا (سلوك معياري في مكتبات الأيقونات).
    'svg_size' => '1em',

    // ==========================================================
    // روابط CDN لتضمين مكتبات الأيقونات تلقائيًا عبر:
    //   @statusKitAssets(['fa','bi','ion'])   أو   status_kit_assets(['fa'])
    // هذا يجنبك تثبيت الحزم يدويًا. للتثبيت المحلي/عبر NPM راجع README.md
    // يمكنك تغيير هذه الروابط أو تحديث الإصدارات من هنا بعد نشر الconfig.
    // ==========================================================
    'cdn' => [
        'fa' => [
            'url' => 'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css',
            'integrity' => 'sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A==',
            'crossorigin' => 'anonymous',
        ],
        'bi' => [
            'url' => 'https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css',
            'integrity' => 'sha512-dPXYcDub/aeb08c63jRq/k6GaKccl256JQy/AnOq7CAnEZ9FzSL9wSbcZkMp4R26vBsMLFYH4kQ67/bbV8XaCQ==',
            'crossorigin' => 'anonymous',
        ],
        'ion' => [
            'url' => 'https://cdn.jsdelivr.net/npm/ionicons@7.1.0/dist/ionicons/ionicons.esm.js',
            'integrity' => null,
            'crossorigin' => 'anonymous',
        ],
        'ion_nomodule' => [
            'url' => 'https://cdn.jsdelivr.net/npm/ionicons@7.1.0/dist/ionicons/ionicons.js',
            'integrity' => null,
            'crossorigin' => 'anonymous',
        ],
    ],

    // ==========================================================
    // FontAwesome (يتطلب تحميل خط/CSS FontAwesome في المشروع)
    // ==========================================================
    'fa' => [
        // ── الأدوار ──
        'super_admin' => 'fa-user-shield',
        'admin' => 'fa-user-gear',
        'support_agent' => 'fa-headset',
        'tech_support' => 'fa-tools',
        'merchant' => 'fa-store',
        'user' => 'fa-user',
        'owner' => 'fa-user-tie',
        'manager' => 'fa-user-tie',
        'staff' => 'fa-user-tie',
        'guest' => 'fa-user',
        'moderator' => 'fa-user-shield',
        'editor' => 'fa-user-edit',
        'support_team' => 'fa-headset',
        'customer' => 'fa-user-circle',
        'billing_manager' => 'fa-file-invoice-dollar',
        'technical_team' => 'fa-laptop-code',
        'qa_team' => 'fa-vial',
        'platform_manager' => 'fa-cogs',
        'deputy_super_admin' => 'fa-user-shield',

        // ── الحالات الأساسية ──
        'default' => 'fa-circle',
        'pending' => 'fa-clock',
        'active' => 'fa-check-circle',
        'inactive' => 'fa-times-circle',
        'paid' => 'fa-check-circle',
        'unpaid' => 'fa-circle-exclamation',
        'failed' => 'fa-circle-exclamation',
        'canceled' => 'fa-ban',
        'cancelled' => 'fa-ban',
        'expired' => 'fa-hourglass-end',
        'success' => 'fa-check',
        'warning' => 'fa-exclamation-triangle',
        'info' => 'fa-info-circle',
        'refunded' => 'fa-rotate-left',
        'suspended' => 'fa-ban',
        'banned' => 'fa-user-slash',
        'rejected' => 'fa-times-circle',
        'approved' => 'fa-check',
        'blocked' => 'fa-lock',
        'draft' => 'fa-file',
        'closed' => 'fa-lock',
        'processing' => 'fa-gear',
        'completed' => 'fa-check-circle',
        'out_of_stock' => 'fa-box-open',
        'discontinued' => 'fa-ban',
        'online' => 'fa-circle',
        'offline' => 'fa-circle-minus',
        'verified' => 'fa-circle-check',
        'unverified' => 'fa-envelope',
        'email_unverified' => 'fa-envelope',
        'archived' => 'fa-box-archive',
        'available' => 'fa-check-circle',
        'unavailable' => 'fa-times-circle',

        // ── أيقونات عامة ──
        'home' => 'fa-home',
        'users' => 'fa-users',
        'settings' => 'fa-cog',
        'logout' => 'fa-sign-out-alt',
        'login' => 'fa-sign-in-alt',
        'register' => 'fa-user-plus',
        'edit' => 'fa-edit',
        'delete' => 'fa-trash',
        'wallet' => 'fa-wallet',
        'money' => 'fa-money-bill-wave',
        'payment' => 'fa-credit-card',
        'transaction' => 'fa-exchange-alt',
        'history' => 'fa-history',
        'search' => 'fa-search',
        'filter' => 'fa-filter',
        'download' => 'fa-download',
        'upload' => 'fa-upload',
        'chart' => 'fa-chart-line',
        'dashboard' => 'fa-tachometer-alt',
        'bell' => 'fa-bell',
        'support' => 'fa-headset',
        'shield' => 'fa-shield-alt',
        'store' => 'fa-store',
        'gold' => 'fa-coins',

        // ── الإشعارات ──
        'new_user' => 'fa-user-plus',
        'new_payment' => 'fa-money-bill-wave',
        'subscription_activated' => 'fa-star',
        'backup_completed' => 'fa-cloud-arrow-up',
        'system_alert' => 'fa-exclamation-triangle',

        // ── أيقونات الأدوار ──
        'shield-exclamation' => 'fa-shield',
        'shield-check' => 'fa-shield',
        'chat-bubble' => 'fa-comment-dots',
        'wrench-screwdriver' => 'fa-wrench',
        'building-storefront' => 'fa-store',
        'user-circle' => 'fa-user-circle',
        'clipboard-check' => 'fa-clipboard-check',
        'pencil-square' => 'fa-pen-square',
        'headset' => 'fa-headset',
        'user-check' => 'fa-user-check',
        'credit-card' => 'fa-credit-card',
        'beaker' => 'fa-flask',
        'server' => 'fa-server',

        // ── بادجات جاهزة ──
        'featured' => 'fa-star',
        'new' => 'fa-bolt',
        'popular' => 'fa-fire',
        'recommended' => 'fa-thumbs-up',
        'limited' => 'fa-hourglass-half',
        'yes' => 'fa-check',
        'no' => 'fa-xmark',
        'on' => 'fa-toggle-on',
        'off' => 'fa-toggle-off',
        'enable' => 'fa-check-circle',
        'disable' => 'fa-ban',
        'open' => 'fa-folder-open',
        'close' => 'fa-times',
        'save' => 'fa-floppy-disk',
        'add' => 'fa-plus',
        'remove' => 'fa-minus',
        'view' => 'fa-eye',
        'email' => 'fa-envelope',
        'phone' => 'fa-phone',
        'calendar' => 'fa-calendar',
        'folder' => 'fa-folder',
        'image' => 'fa-image',
        'message' => 'fa-envelope',
        'send' => 'fa-paper-plane',
        'share' => 'fa-share-nodes',
        'cart' => 'fa-cart-shopping',
        'star' => 'fa-star',
        'heart' => 'fa-heart',
        'flag' => 'fa-flag',
        'check' => 'fa-check',
        'cross' => 'fa-xmark',
        'plus' => 'fa-plus',
        'minus' => 'fa-minus',
        'key' => 'fa-key',
        'lock' => 'fa-lock',
        'unlock' => 'fa-lock-open',
        'link' => 'fa-link',
        'help' => 'fa-circle-question',
        'refresh' => 'fa-rotate',
        'eye' => 'fa-eye',
        'eye-off' => 'fa-eye-slash',
        'play' => 'fa-play',
        'pause' => 'fa-pause',
        'stop' => 'fa-stop',
        'rewind' => 'fa-backward',
        'forward' => 'fa-forward',
        'next' => 'fa-forward-step',
        'prev' => 'fa-backward-step',
        'repeat' => 'fa-repeat',
        'shuffle' => 'fa-shuffle',
        'volume' => 'fa-volume-high',
        'volume-mute' => 'fa-volume-xmark',
        'play-circle' => 'fa-circle-play',
        'pause-circle' => 'fa-circle-pause',

        // ── دورة حياة + إضافات v1.1.4 ──
        'beta' => 'fa-flask',
        'deprecated' => 'fa-triangle-exclamation',
        'locked' => 'fa-lock',
        'unlocked' => 'fa-lock-open',
        'highlighted' => 'fa-highlighter',
        'trending' => 'fa-arrow-trend-up',
        'restored' => 'fa-rotate',
        'published' => 'fa-cloud-arrow-up',
        'unpublished' => 'fa-cloud',
        'submitted' => 'fa-paper-plane',
        'reviewed' => 'fa-magnifying-glass',
        'under_review' => 'fa-magnifying-glass',
        'deleted' => 'fa-trash',
        'confirmed' => 'fa-circle-check',
        'preparing' => 'fa-gear',
        'shipped' => 'fa-truck',
        'delivered' => 'fa-box',
        'returned' => 'fa-rotate-left',
        'in_transit' => 'fa-truck-fast',
        'on_hold' => 'fa-hand',
        'out_for_delivery' => 'fa-truck',
        'critical' => 'fa-circle-exclamation',
        'upcoming' => 'fa-calendar',
        'ongoing' => 'fa-spinner',
        'ended' => 'fa-stop-circle',
        'paused' => 'fa-circle-pause',
        'resumed' => 'fa-circle-play',
        'scheduled' => 'fa-calendar-check',
        'delayed' => 'fa-clock',
        'trial' => 'fa-flask',
        'active_subscription' => 'fa-star',
        'expired_subscription' => 'fa-hourglass-end',
        'renewed' => 'fa-rotate',
        'upgraded' => 'fa-arrow-up',
        'downgraded' => 'fa-arrow-down',
        'confirmed_email' => 'fa-envelope-circle-check',
        'unconfirmed_email' => 'fa-envelope',
        'password_reset' => 'fa-key',
        'unknown' => 'fa-question-circle',
    ],

    // ==========================================================
    // Bootstrap Icons
    // ==========================================================
    'bi' => [
        // ── الحالات الأساسية ──
        'default' => 'bi-circle',
        'pending' => 'bi-clock',
        'active' => 'bi-check-circle',
        'inactive' => 'bi-x-circle',
        'paid' => 'bi-check-circle',
        'unpaid' => 'bi-x-circle',
        'failed' => 'bi-x-circle',
        'canceled' => 'bi-slash-circle',
        'cancelled' => 'bi-slash-circle',
        'expired' => 'bi-hourglass-split',
        'success' => 'bi-check-lg',
        'warning' => 'bi-exclamation-triangle',
        'info' => 'bi-info-circle',
        'refunded' => 'bi-arrow-counterclockwise',
        'suspended' => 'bi-slash-circle',
        'banned' => 'bi-person-x',
        'rejected' => 'bi-x-circle',
        'approved' => 'bi-check-lg',
        'blocked' => 'bi-lock',
        'draft' => 'bi-file-earmark',
        'closed' => 'bi-lock',
        'processing' => 'bi-gear',
        'completed' => 'bi-check-circle',
        'out_of_stock' => 'bi-box-seam',
        'discontinued' => 'bi-slash-circle',
        'email_unverified' => 'bi-envelope',
        'online' => 'bi-circle-fill',
        'offline' => 'bi-circle',
        'verified' => 'bi-patch-check-fill',
        'unverified' => 'bi-envelope',
        'archived' => 'bi-archive-fill',
        'available' => 'bi-check-circle',
        'unavailable' => 'bi-x-circle',

        // ── أيقونات عامة ──
        'home' => 'bi-house',
        'user' => 'bi-person',
        'users' => 'bi-people',
        'settings' => 'bi-gear',
        'logout' => 'bi-box-arrow-right',
        'login' => 'bi-box-arrow-in-right',
        'register' => 'bi-person-plus',
        'edit' => 'bi-pencil',
        'delete' => 'bi-trash',
        'wallet' => 'bi-wallet2',
        'money' => 'bi-cash',
        'payment' => 'bi-credit-card',
        'transaction' => 'bi-arrow-left-right',
        'history' => 'bi-clock-history',
        'search' => 'bi-search',
        'filter' => 'bi-funnel',
        'download' => 'bi-download',
        'upload' => 'bi-upload',
        'chart' => 'bi-graph-up',
        'dashboard' => 'bi-speedometer2',
        'bell' => 'bi-bell',
        'support' => 'bi-headset',
        'shield' => 'bi-shield-check',
        'store' => 'bi-shop',
        'gold' => 'bi-coin',

        // ── الإشعارات ──
        'new_user' => 'bi-person-plus',
        'new_payment' => 'bi-cash-stack',
        'subscription_activated' => 'bi-stars',
        'backup_completed' => 'bi-cloud-check',
        'system_alert' => 'bi-exclamation-triangle',

        // ── أيقونات الأدوار ──
        'shield-exclamation' => 'bi-shield-exclamation',
        'shield-check' => 'bi-shield-check',
        'chat-bubble' => 'bi-chat-dots',
        'wrench-screwdriver' => 'bi-wrench',
        'building-storefront' => 'bi-shop',
        'user-circle' => 'bi-person-circle',
        'clipboard-check' => 'bi-clipboard-check',
        'pencil-square' => 'bi-pencil-square',
        'headset' => 'bi-headset',
        'user-check' => 'bi-person-check',
        'credit-card' => 'bi-credit-card',
        'beaker' => 'bi-flask',
        'server' => 'bi-server',

        // ── بادجات جاهزة ──
        'featured' => 'bi-star-fill',
        'new' => 'bi-lightning-charge-fill',
        'popular' => 'bi-fire',
        'recommended' => 'bi-hand-thumbs-up-fill',
        'limited' => 'bi-hourglass-split',
        'yes' => 'bi-check-circle-fill',
        'no' => 'bi-x-circle-fill',
        'on' => 'bi-toggle-on',
        'off' => 'bi-toggle-off',
        'enable' => 'bi-check-circle',
        'disable' => 'bi-slash-circle',
        'open' => 'bi-folder2-open',
        'close' => 'bi-x-lg',
        'save' => 'bi-floppy',
        'add' => 'bi-plus-lg',
        'remove' => 'bi-dash-lg',
        'view' => 'bi-eye',
        'email' => 'bi-envelope',
        'phone' => 'bi-telephone',
        'calendar' => 'bi-calendar3',
        'folder' => 'bi-folder2',
        'image' => 'bi-image',
        'message' => 'bi-envelope',
        'send' => 'bi-send',
        'share' => 'bi-share',
        'cart' => 'bi-cart3',
        'star' => 'bi-star-fill',
        'heart' => 'bi-heart-fill',
        'flag' => 'bi-flag-fill',
        'check' => 'bi-check-lg',
        'cross' => 'bi-x-lg',
        'plus' => 'bi-plus-lg',
        'minus' => 'bi-dash-lg',
        'key' => 'bi-key-fill',
        'lock' => 'bi-lock-fill',
        'unlock' => 'bi-unlock-fill',
        'link' => 'bi-link-45deg',
        'help' => 'bi-question-circle-fill',
        'refresh' => 'bi-arrow-clockwise',
        'eye' => 'bi-eye',
        'eye-off' => 'bi-eye-slash',
        'play' => 'bi-play-fill',
        'pause' => 'bi-pause-fill',
        'stop' => 'bi-stop-fill',
        'rewind' => 'bi-skip-backward-fill',
        'forward' => 'bi-skip-forward-fill',
        'next' => 'bi-skip-end-fill',
        'prev' => 'bi-skip-start-fill',
        'repeat' => 'bi-arrow-repeat',
        'shuffle' => 'bi-shuffle',
        'volume' => 'bi-volume-up-fill',
        'volume-mute' => 'bi-volume-mute-fill',
        'play-circle' => 'bi-play-circle-fill',
        'pause-circle' => 'bi-pause-circle-fill',

        // ── دورة حياة + إضافات v1.1.4 ──
        'beta' => 'bi-flask',
        'deprecated' => 'bi-exclamation-triangle-fill',
        'locked' => 'bi-lock-fill',
        'unlocked' => 'bi-unlock-fill',
        'highlighted' => 'bi-highlighter',
        'trending' => 'bi-graph-up-arrow',
        'restored' => 'bi-arrow-clockwise',
        'published' => 'bi-cloud-arrow-up-fill',
        'unpublished' => 'bi-cloud',
        'submitted' => 'bi-send-fill',
        'reviewed' => 'bi-search',
        'under_review' => 'bi-search',
        'deleted' => 'bi-trash-fill',
        'confirmed' => 'bi-check-circle-fill',
        'preparing' => 'bi-gear',
        'shipped' => 'bi-truck',
        'delivered' => 'bi-box-seam',
        'returned' => 'bi-arrow-return-left',
        'in_transit' => 'bi-truck',
        'on_hold' => 'bi-pause-circle',
        'out_for_delivery' => 'bi-truck',
        'critical' => 'bi-exclamation-octagon-fill',
        'upcoming' => 'bi-calendar-event',
        'ongoing' => 'bi-play-circle',
        'ended' => 'bi-stop-circle-fill',
        'paused' => 'bi-pause-circle-fill',
        'resumed' => 'bi-play-circle-fill',
        'scheduled' => 'bi-calendar-check',
        'delayed' => 'bi-clock-history',
        'trial' => 'bi-flask',
        'active_subscription' => 'bi-star-fill',
        'expired_subscription' => 'bi-hourglass-end',
        'renewed' => 'bi-arrow-repeat',
        'upgraded' => 'bi-arrow-up-circle-fill',
        'downgraded' => 'bi-arrow-down-circle',
        'confirmed_email' => 'bi-envelope-check-fill',
        'unconfirmed_email' => 'bi-envelope',
        'password_reset' => 'bi-key-fill',
        'unknown' => 'bi-question-circle',
    ],

    // ==========================================================
    // Ionicons
    // ==========================================================
    'ion' => [
        // ── الحالات الأساسية ──
        'default' => 'ellipse-outline',
        'pending' => 'time-outline',
        'active' => 'checkmark-circle-outline',
        'inactive' => 'close-circle-outline',
        'paid' => 'checkmark-done-circle-outline',
        'unpaid' => 'alert-circle-outline',
        'failed' => 'alert-circle-outline',
        'canceled' => 'ban-outline',
        'cancelled' => 'ban-outline',
        'expired' => 'hourglass-outline',
        'success' => 'checkmark-outline',
        'warning' => 'warning-outline',
        'info' => 'information-circle-outline',
        'refunded' => 'refresh-outline',
        'suspended' => 'ban-outline',
        'banned' => 'person-remove-outline',
        'rejected' => 'close-circle-outline',
        'approved' => 'checkmark-outline',
        'blocked' => 'lock-closed-outline',
        'draft' => 'document-outline',
        'closed' => 'lock-closed-outline',
        'processing' => 'settings-outline',
        'completed' => 'checkmark-done-circle-outline',
        'out_of_stock' => 'cube-outline',
        'discontinued' => 'ban-outline',
        'email_unverified' => 'mail-outline',
        'online' => 'radio-button-on-outline',
        'offline' => 'radio-button-off-outline',
        'verified' => 'shield-checkmark-outline',
        'unverified' => 'mail-outline',
        'archived' => 'archive-outline',
        'available' => 'checkmark-circle-outline',
        'unavailable' => 'close-circle-outline',

        // ── أيقونات عامة ──
        'wallet' => 'wallet-outline',
        'card' => 'card-outline',
        'cash' => 'cash-outline',
        'bank' => 'business-outline',
        'tag' => 'pricetag-outline',
        'tags' => 'pricetags-outline',
        'transaction' => 'swap-horizontal-outline',
        'repeat' => 'repeat-outline',
        'receipt' => 'receipt-outline',
        'history' => 'file-tray-full-outline',
        'trend-up' => 'trending-up-outline',
        'trend-down' => 'trending-down-outline',
        'login' => 'log-in-outline',
        'logout' => 'log-out-outline',
        'register' => 'person-add-outline',
        'user' => 'person-outline',
        'settings' => 'settings-outline',
        'home' => 'home-outline',
        'dashboard' => 'grid-outline',
        'edit' => 'create-outline',
        'save' => 'save-outline',
        'delete' => 'trash-outline',
        'add' => 'add-outline',
        'minus' => 'remove-circle-outline',
        'eye' => 'eye-outline',
        'eye-off' => 'eye-off-outline',
        'reset' => 'refresh-outline',
        'copy' => 'copy-outline',
        'chevron-down' => 'chevron-down-outline',
        'chevron-up' => 'chevron-up-outline',
        'chevron-left' => 'chevron-back-outline',
        'chevron-right' => 'chevron-forward-outline',
        'arrow-up' => 'arrow-up-outline',
        'arrow-down' => 'arrow-down-outline',
        'arrow-left' => 'arrow-back-outline',
        'arrow-right' => 'arrow-forward-outline',
        'search' => 'search-outline',
        'filter' => 'funnel-outline',
        'download' => 'download-outline',
        'upload' => 'upload-outline',
        'bell' => 'notifications-outline',
        'help' => 'help-circle-outline',
        'shield' => 'shield-checkmark-outline',
        'qrcode' => 'qr-code-outline',
        'menu' => 'menu-outline',
        'apps' => 'apps-outline',
        'store' => 'storefront-outline',
        'gold' => 'gem-outline',
        'chart' => 'bar-chart-outline',

        // ── الإشعارات ──
        'new_user' => 'person-add-outline',
        'new_payment' => 'cash-outline',
        'subscription_activated' => 'star-outline',
        'backup_completed' => 'cloud-done-outline',
        'system_alert' => 'warning-outline',

        // ── أيقونات الأدوار ──
        'shield-exclamation' => 'shield-outline',
        'shield-check' => 'shield-checkmark-outline',
        'chat-bubble' => 'chatbubble-ellipses-outline',
        'wrench-screwdriver' => 'wrench-outline',
        'building-storefront' => 'storefront-outline',
        'user-circle' => 'person-circle-outline',
        'clipboard-check' => 'clipboard-outline',
        'pencil-square' => 'pencil-outline',
        'headset' => 'headset-outline',
        'user-check' => 'person-outline',
        'credit-card' => 'card-outline',
        'beaker' => 'flask-outline',
        'server' => 'server-outline',

        // ── بادجات جاهزة ──
        'featured' => 'star',
        'new' => 'flash-outline',
        'popular' => 'flame-outline',
        'recommended' => 'thumbs-up-outline',
        'limited' => 'hourglass-outline',
        'yes' => 'checkmark-outline',
        'no' => 'close-outline',
        'on' => 'toggle-outline',
        'off' => 'toggle-outline',
        'enable' => 'checkmark-circle-outline',
        'disable' => 'ban-outline',
        'open' => 'folder-open-outline',
        'close' => 'close-outline',
        'save' => 'save-outline',
        'add' => 'add-outline',
        'remove' => 'remove-outline',
        'view' => 'eye-outline',
        'email' => 'mail-outline',
        'phone' => 'call-outline',
        'calendar' => 'calendar-outline',
        'folder' => 'folder-outline',
        'image' => 'image-outline',
        'message' => 'chatbox-ellipses-outline',
        'send' => 'send-outline',
        'share' => 'share-outline',
        'cart' => 'cart-outline',
        'star' => 'star',
        'heart' => 'heart-outline',
        'flag' => 'flag-outline',
        'check' => 'checkmark-outline',
        'cross' => 'close-outline',
        'plus' => 'add-outline',
        'minus' => 'remove-outline',
        'key' => 'key-outline',
        'lock' => 'lock-closed-outline',
        'unlock' => 'lock-open-outline',
        'link' => 'link-outline',
        'help' => 'help-circle-outline',
        'refresh' => 'refresh-outline',
        'play' => 'play-outline',
        'pause' => 'pause-outline',
        'stop' => 'stop-outline',
        'rewind' => 'play-back-outline',
        'forward' => 'play-forward-outline',
        'next' => 'play-forward-outline',
        'prev' => 'play-back-outline',
        'repeat' => 'repeat-outline',
        'shuffle' => 'shuffle-outline',
        'volume' => 'volume-high-outline',
        'volume-mute' => 'volume-mute-outline',
        'play-circle' => 'play-circle-outline',
        'pause-circle' => 'pause-circle-outline',

        // ── دورة حياة + إضافات v1.1.4 ──
        'beta' => 'flask-outline',
        'deprecated' => 'warning-outline',
        'locked' => 'lock-closed-outline',
        'unlocked' => 'lock-open-outline',
        'highlighted' => 'ribbon-outline',
        'trending' => 'trending-up-outline',
        'restored' => 'refresh-circle-outline',
        'published' => 'cloud-upload-outline',
        'unpublished' => 'cloud-outline',
        'submitted' => 'paper-plane-outline',
        'reviewed' => 'search-outline',
        'under_review' => 'search-outline',
        'deleted' => 'trash-outline',
        'confirmed' => 'checkmark-done-circle-outline',
        'preparing' => 'settings-outline',
        'shipped' => 'car-outline',
        'delivered' => 'cube-outline',
        'returned' => 'return-down-back-outline',
        'in_transit' => 'car-outline',
        'on_hold' => 'pause-circle-outline',
        'out_for_delivery' => 'car-outline',
        'critical' => 'alert-circle-outline',
        'upcoming' => 'calendar-outline',
        'ongoing' => 'play-circle-outline',
        'ended' => 'stop-circle-outline',
        'paused' => 'pause-circle-outline',
        'resumed' => 'play-circle-outline',
        'scheduled' => 'calendar-outline',
        'delayed' => 'time-outline',
        'trial' => 'flask-outline',
        'active_subscription' => 'star-outline',
        'expired_subscription' => 'hourglass-outline',
        'renewed' => 'refresh-outline',
        'upgraded' => 'arrow-up-circle-outline',
        'downgraded' => 'arrow-down-circle-outline',
        'confirmed_email' => 'mail-open-outline',
        'unconfirmed_email' => 'mail-outline',
        'password_reset' => 'key-outline',
        'unknown' => 'help-circle-outline',
    ],

    // ==========================================================
    // Heroicons (Outline) — تُعرض كـ SVG من resources/svg/heroicons
    // القيمة هنا = اسم ملف الـ SVG بدون امتداد داخل resources/svg/heroicons/
    // ==========================================================
    'heroicon' => [
        // ── الحالات الأساسية ──
        'default' => 'ellipsis-horizontal-circle',
        'pending' => 'clock',
        'active' => 'check-circle',
        'inactive' => 'x-circle',
        'paid' => 'currency-dollar',
        'unpaid' => 'x-circle',
        'failed' => 'x-circle',
        'canceled' => 'x-mark',
        'cancelled' => 'x-mark',
        'expired' => 'x-circle',
        'success' => 'check-circle',
        'warning' => 'exclamation-triangle',
        'info' => 'information-circle',
        'refunded' => 'arrow-path',
        'suspended' => 'exclamation-circle',
        'banned' => 'x-circle',
        'rejected' => 'x-circle',
        'approved' => 'check-circle',
        'blocked' => 'lock-closed',
        'draft' => 'lock-open',
        'closed' => 'lock-closed',
        'processing' => 'cog',
        'completed' => 'check-circle',
        'out_of_stock' => 'exclamation-triangle',
        'discontinued' => 'x-mark',
        'email_unverified' => 'envelope',
        'online' => 'check-circle',
        'offline' => 'x-circle',
        'verified' => 'check-circle',
        'unverified' => 'envelope',
        'archived' => 'lock-closed',
        'available' => 'check-circle',
        'unavailable' => 'x-circle',

        // ── الأدوار ──
        'shield-exclamation' => 'shield-exclamation',
        'shield-check' => 'shield-check',
        'chat-bubble' => 'chat-bubble-left-right',
        'wrench-screwdriver' => 'wrench-screwdriver',
        'building-storefront' => 'building-storefront',
        'user-circle' => 'user-circle',
        'user' => 'user',
        'clipboard-check' => 'clipboard-document-check',

        // ── الإشعارات ──
        'new_user' => 'user',
        'new_payment' => 'currency-dollar',
        'subscription_activated' => 'star',
        'backup_completed' => 'arrow-path',
        'system_alert' => 'exclamation-triangle',

        // ── بادجات جاهزة ──
        'featured' => 'star',
        'new' => 'bolt',
        'popular' => 'fire',
        'recommended' => 'hand-thumb-up',
        'limited' => 'flag',
        'yes' => 'check-circle',
        'no' => 'x-circle',
        'on' => 'check-circle',
        'off' => 'x-circle',
        'enable' => 'check-circle',
        'disable' => 'x-circle',
        'open' => 'folder-open',
        'close' => 'x-mark',
        'save' => 'document-arrow-down',
        'add' => 'plus',
        'remove' => 'minus',
        'view' => 'eye',
        'email' => 'envelope',
        'phone' => 'check-circle',
        'calendar' => 'clock',
        'folder' => 'folder-open',
        'image' => 'photo',
        'message' => 'envelope',
        'send' => 'paper-airplane',
        'share' => 'paper-airplane',
        'cart' => 'shopping-cart',
        'heart' => 'heart',
        'check' => 'check-circle',
        'cross' => 'x-mark',
        'plus' => 'plus',
        'minus' => 'minus',
        'key' => 'key',
        'lock' => 'lock-closed',
        'unlock' => 'lock-open',
        'link' => 'link',
        'help' => 'question-mark-circle',
        'refresh' => 'arrow-path',
        'eye' => 'eye',
        'eye-off' => 'eye-slash',
        'play' => 'play',
        'pause' => 'pause',
        'stop' => 'stop',
        'rewind' => 'backward',
        'forward' => 'forward',
        'next' => 'forward',
        'prev' => 'backward',
        'repeat' => 'arrow-path',
        'volume' => 'speaker-wave',
        'volume-mute' => 'speaker-x-mark',
        'play-circle' => 'play-circle',
        'pause-circle' => 'pause-circle',

        // ── دورة حياة + إضافات v1.1.4 ──
        'beta' => 'exclamation-circle',
        'deprecated' => 'exclamation-triangle',
        'locked' => 'lock-closed',
        'unlocked' => 'lock-open',
        'delete' => 'x-mark',
        'highlighted' => 'star',
        'trending' => 'arrow-path',
        'restored' => 'arrow-path',
        'published' => 'arrow-path',
        'unpublished' => 'x-mark',
        'submitted' => 'paper-airplane',
        'reviewed' => 'check-circle',
        'under_review' => 'check-circle',
        'deleted' => 'x-circle',
        'confirmed' => 'check-circle',
        'preparing' => 'cog',
        'shipped' => 'arrow-path',
        'delivered' => 'check-circle',
        'returned' => 'backward',
        'in_transit' => 'arrow-path',
        'on_hold' => 'pause-circle',
        'out_for_delivery' => 'arrow-path',
        'critical' => 'exclamation-triangle',
        'upcoming' => 'clock',
        'ongoing' => 'play-circle',
        'ended' => 'x-circle',
        'paused' => 'pause-circle',
        'resumed' => 'play-circle',
        'scheduled' => 'clock',
        'delayed' => 'clock',
        'trial' => 'question-mark-circle',
        'active_subscription' => 'star',
        'expired_subscription' => 'x-circle',
        'renewed' => 'arrow-path',
        'upgraded' => 'check-circle',
        'downgraded' => 'x-circle',
        'confirmed_email' => 'check-circle',
        'unconfirmed_email' => 'envelope',
        'password_reset' => 'key',
        'unknown' => 'question-mark-circle',
    ],
];
